### ISSUE TITLE
Set route type of flex routes to 715

### ISSUE THREAD

**Issue by leonardehrenfried** [derhuerst/generate-herrenberg-gtfs-flex#3]
This corresponds to On Demand Service: https://developers.google.com/transit/gtfs/reference/extended-route-types

/cc @andreashelms

**Comment by derhuerst** [comment]
FYI The latest Docker image `fc68af8a8f6e3aa8b349f07ec42d40707f0811b880238dea8ac559500dda541e` now sets `route_type: 715` for all specified GTFS-Flex routes.
