### ISSUE TITLE
Remove sentence referencing "Fr. Schmauderer"

### ISSUE THREAD

**Issue by leonardehrenfried** [derhuerst/generate-herrenberg-gtfs-flex#4]
This was meant as directions for the person on the stadtnavi team researching the exact conditions of the flex taxi. :)

Please replace it with a generic message: "Haustürbedienung innerhalb von 300m einer Bushaltestelle gegen Aufpreis von 1€ möglich".

**Comment by leonardehrenfried** [comment]
cc @hbruch

**Comment by derhuerst** [comment]
The name of the person is already removed as of 7af57a677a20140611be498c87dea25d934e61f7.

> "Haustürbedienung innerhalb von 300m einer Bushaltestelle gegen Aufpreis von 1€ möglich".

The 300m rule applies to *Regionalbusse* as well?

I feel like we have a tedious communication ping-pong here. Please take a look at the 2 rules in place, they should be reasonably easy to read:

https://github.com/derhuerst/generate-herrenberg-gtfs-flex/blob/10ee86f4eff629532abe976bd3644aaf5b44c329/herrenberg-flex-rules.js#L7-L56

**Comment by leonardehrenfried** [comment]
Fair point.

**Comment by derhuerst** [comment]
FYI The latest Docker image `fc68af8a8f6e3aa8b349f07ec42d40707f0811b880238dea8ac559500dda541e` doesn't mention the person anymore.
