### ISSUE TITLE
Duplicate stop locations in flex trips

### ISSUE THREAD

**Issue by leonardehrenfried** [derhuerst/generate-herrenberg-gtfs-flex#5]
Related to https://github.com/mfdz/OpenTripPlanner/issues/101

In order to implement Herrenberg's on demand taxi rules where you are only allowed to get on the taxi at a bus stop but off the taxi anywhere inside a 300m radius of a stop, we decided on the following implementation:

- for pick up an actual `Stop` is included
- for drop off a `Location` is included

And so every `stop_times` row would be present twice:

- bus station stop (drop_off_type=1)
- bus station location (pickup_type=1)

/cc @flaktack @hbruch

Since this might confuse the production system, please create a new feed hbg4.

Fixes: https://github.com/stadtnavi/digitransit-ui/issues/571

**Comment by derhuerst** [comment]
So, to clarify, a trip `trip-1` should look like this within `stop_times`?

`trip_id` | `stop_sequence` | `stop_id` | `arrival_time` | `departure_time` | `start_pickup_dropoff_window` | `end_pickup_dropoff_window` | `pickup_type` | `drop_off_type` | `pickup_booking_rule_id` | `drop_off_booking_rule_id`
-|-|-|-|-|-|-|-|-|-|-
`trip-1` | `0` | `A` | `15:13:13` | `15:13:13` | | | `2` | `3` | `herrenberg-rufbusse` | `herrenberg-rufbusse`
`trip-1` | `1` | `B` | `15:23:23` | `15:23:23` | | | `2` | `3` | `herrenberg-rufbusse` | `herrenberg-rufbusse`
`trip-1` | `2` | `C` | `15:33:33` | `15:33:33` | | | `2` | `3` | `herrenberg-rufbusse` | `herrenberg-rufbusse`
`trip-1` | `0` | `A` | `15:13:13` | `15:13:13` | `15:12:43` | `15:13:43` | `2` | `3` | `herrenberg-rufbusse` | `herrenberg-rufbusse`
`trip-1` | `1` | `B` | `15:23:23` | `15:23:23` | `15:22:53` | `15:23:53` | `2` | `3` | `herrenberg-rufbusse` | `herrenberg-rufbusse`
`trip-1` | `2` | `C` | `15:33:33` | `15:33:33` | `15:33:03` | `15:34:03` | `2` | `3` | `herrenberg-rufbusse` | `herrenberg-rufbusse`

**Comment by derhuerst** [comment]
`trip_id` | `arrival_time` | `departure_time` | `stop_id` | `stop_sequence` | `stop_headsign` | `pickup_type` | `drop_off_type` | `shape_dist_traveled` | `pickup_booking_rule_id` | `drop_off_booking_rule_id` | `start_pickup_dropoff_window` | `end_pickup_dropoff_window` | `timepoint`
-|-|-|-|-|-|-|-|-|-|-|-|-|-
`1.T0.50-779-j21-1.1.H` | `21:51:00` | `21:51:00` | `de:08115:4512:5:F` | `1` | `Im Vogelsang` | `0` | `1` | `0.00` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `21:52:00` | `21:52:00` | `de:08115:3237:0:3` | `2` | | `0` | `1` | `339.34` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `21:53:00` | `21:53:00` | `de:08115:7055:0:3` | `3` | | `0` | `1` | `798.67` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `21:54:00` | `21:54:00` | `de:08115:7056:0:3` | `4` | | `0` | `1` | `934.77` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `21:55:00` | `21:55:00` | `de:08115:7057:0:3` | `5` | `Herrenberg ZOB` | `0` | `1` | `1186.29` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `21:56:00` | `21:56:00` | `de:08115:7042:0:3` | `6` | | `0` | `1` | `1599.97` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `21:57:00` | `21:57:00` | `de:08115:7059:0:3` | `7` | | `0` | `1` | `2010.65` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `21:58:00` | `21:58:00` | `de:08115:7040:0:3` | `8` | | `0` | `1` | `2202.08` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | `22:01:00` | `22:01:00` | `de:08115:4512:5:F` | `9` | | `0` | `1` | `3193.27` | `herrenberg-citybus` | `herrenberg-citybus` | | | `1`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:4512:5:F-flex` | `1` | `Im Vogelsang` | `1` | `3` | `0.00` | `herrenberg-citybus` | `herrenberg-citybus` | `21:50:30` | `21:51:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:3237:0:3-flex` | `2` | | `1` | `3` | `339.34` | `herrenberg-citybus` | `herrenberg-citybus` | `21:51:30` | `21:52:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:7055:0:3-flex` | `3` | | `1` | `3` | `798.67` | `herrenberg-citybus` | `herrenberg-citybus` | `21:52:30` | `21:53:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:7056:0:3-flex` | `4` | | `1` | `3` | `934.77` | `herrenberg-citybus` | `herrenberg-citybus` | `21:53:30` | `21:54:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:7057:0:3-flex` | `5` | `Herrenberg ZOB` | `1` | `3` | `1186.29` | `herrenberg-citybus` | `herrenberg-citybus` | `21:54:30` | `21:55:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:7042:0:3-flex` | `6` | | `1` | `3` | `1599.97` | `herrenberg-citybus` | `herrenberg-citybus` | `21:55:30` | `21:56:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:7059:0:3-flex` | `7` | | `1` | `3` | `2010.65` | `herrenberg-citybus` | `herrenberg-citybus` | `21:56:30` | `21:57:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:7040:0:3-flex` | `8` | | `1` | `3` | `2202.08` | `herrenberg-citybus` | `herrenberg-citybus` | `21:57:30` | `21:58:30` | `0`
`1.T0.50-779-j21-1.1.H` | | | `herrenberg-citybus-300m-de:08115:4512:5:F-flex` | `9` | | `1` | `3` | `3193.27` | `herrenberg-citybus` | `herrenberg-citybus` | `22:00:30` | `22:01:30` | `0`
